// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: reservation.proto

package ma.projet.hotel.grpc;

public interface GetAllReservationsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllReservationsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ReservationResponse reservations = 1;</code>
   */
  java.util.List<ma.projet.hotel.grpc.ReservationResponse> 
      getReservationsList();
  /**
   * <code>repeated .ReservationResponse reservations = 1;</code>
   */
  ma.projet.hotel.grpc.ReservationResponse getReservations(int index);
  /**
   * <code>repeated .ReservationResponse reservations = 1;</code>
   */
  int getReservationsCount();
  /**
   * <code>repeated .ReservationResponse reservations = 1;</code>
   */
  java.util.List<? extends ma.projet.hotel.grpc.ReservationResponseOrBuilder> 
      getReservationsOrBuilderList();
  /**
   * <code>repeated .ReservationResponse reservations = 1;</code>
   */
  ma.projet.hotel.grpc.ReservationResponseOrBuilder getReservationsOrBuilder(
      int index);
}
